version: "3.8"

name: "full-stack-app"

services:
  backend:
    init: true
    image: "mcr.microsoft.com/devcontainers/java:1-21-bullseye"
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspaces:cached
  frontend:
    init: true
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye"
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/workspaces:cached
  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
